version: '3.8'
services:
  pg-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sales_data
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  webserver:
    image: apache/airflow:2.3.0
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__EXECUTOR: 'LocalExecutor'
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'postgresql+psycopg2://admin:password@pg-db/sales_data'
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
      AIRFLOW__CORE__FERNET_KEY: 'wKs35lvEqa8EZR41DMgJi3hDgW3h9Jr_ckRkxRTtuF4='
    ports:
      - "8080:8080"
    volumes:
      - airflow_dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    depends_on:
      - pg-db

  scheduler:
    image: apache/airflow:2.3.0
    environment:
      AIRFLOW__CORE__EXECUTOR: 'LocalExecutor'
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'postgresql+psycopg2://admin:password@pg-db/sales_data'
    volumes:
      - airflow_dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
    depends_on:
      - pg-db
    command: scheduler

volumes:
  pg-data:
    driver: local
  airflow_dags:
    driver: local
  airflow_logs:
    driver: local
  airflow_plugins:
    driver: local
